In [2]:
import numpy as np
import tensorflow as tf
import torch 
import matplotlib.pyplot as plt

##The Frobenius Norm

In [ ]:
#This is like the L2 norm for vectors but it takes the summation of the square of each xij and takes the square root!

In [3]:
#Let us create a matrix using numpy

In [5]:
X_np = np.array([[2,3,4],[5,-2,4],[5,0,9]])
X_np

array([[ 2,  3,  4],
       [ 5, -2,  4],
       [ 5,  0,  9]])

In [6]:
#We get the Frobenius norm
np.linalg.norm(X_np)


13.416407864998739

In [7]:
#Using PyTorch

In [12]:
X_pt = torch.tensor([[2,3,4],[5,-2,4],[5,0,9.]]) #It requires our values to be floats
X_pt

tensor([[ 2.,  3.,  4.],
        [ 5., -2.,  4.],
        [ 5.,  0.,  9.]])

In [13]:
torch.norm(X_pt)

tensor(13.4164)

In [14]:
#Using Tensor Flow

In [15]:
X_tf = tf.Variable([[2,3,4],[5,-2,4],[5,0,9.]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 2.,  3.,  4.],
       [ 5., -2.,  4.],
       [ 5.,  0.,  9.]], dtype=float32)>

In [16]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=13.416408>

## Matrix Multiplication

In [18]:
#Using numpy
#numpy uses dot to multiply matrices
Y_np = np.array([[2,4],[-2,0],[1,6]])
Y_np

array([[ 2,  4],
       [-2,  0],
       [ 1,  6]])

In [19]:
np.dot(X_np,Y_np)

array([[ 2, 32],
       [18, 44],
       [19, 74]])

In [27]:
#Using pytorch

Y_pt = torch.tensor([[2,4],[-2,0],[1,6.]])
Y_pt

tensor([[ 2.,  4.],
        [-2.,  0.],
        [ 1.,  6.]])

In [28]:
torch.matmul(X_pt,Y_pt)

tensor([[ 2., 32.],
        [18., 44.],
        [19., 74.]])

In [29]:
#Using tensorflow
Y_tf = tf.Variable([[2,4],[-2,0],[1,6.]])
Y_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 2.,  4.],
       [-2.,  0.],
       [ 1.,  6.]], dtype=float32)>

In [30]:
tf.matmul(X_tf,Y_tf)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 2., 32.],
       [18., 44.],
       [19., 74.]], dtype=float32)>

##Symmetric and Identity Matrices

In [32]:
#Symmetric Matrices are square matrices with the transpose is equal to the matrix
#A special case is the identity matrices

In [33]:
X_sym = np.array([[0,1,2],[1,7,8],[2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [34]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [38]:
I = np.array([[1,0,0],[0,1,0],[0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
I.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [40]:
np.dot(X_np,I)

array([[ 2,  3,  4],
       [ 5, -2,  4],
       [ 5,  0,  9]])

##Matrix Inversion

In [41]:
#X*X^-1 = I

In [42]:
X_np

array([[ 2,  3,  4],
       [ 5, -2,  4],
       [ 5,  0,  9]])

In [53]:
np.linalg.det(X_np) #The determinant 

-71.0

In [57]:
X_np_inv = np.linalg.inv(X_np) #The inverse
X_np_inv

array([[ 0.25352113,  0.38028169, -0.28169014],
       [ 0.35211268,  0.02816901, -0.16901408],
       [-0.14084507, -0.21126761,  0.26760563]])

In [58]:
np.dot(X_np,X_np_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.22044605e-16,  1.00000000e+00, -2.22044605e-16],
       [ 2.77555756e-16, -5.55111512e-17,  1.00000000e+00]])

##Diagonal Matrices


In [59]:
#All other entries is zero expect non zero in its leading diagonal 

In [60]:
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

##Orthogonal Matrices

In [63]:
#These are special types of matrices that all the rows are orthogonal vectors and when you get the column they are orthogonal too
#They have some special properties A* A(transpose) is I

In [62]:
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])